{"name": "异常用例: 姓名-, 账号-账号, 手机号-手机, 邮箱-邮箱", "status": "passed", "attachments": [{"name": "测试图片", "source": "05d6665e-e1f6-4250-8173-6b87bb4f793b-attachment.png", "type": "image/png"}], "parameters": [{"name": "get_add_member_fail_datas", "value": "['', '账号', '手机', '邮箱', 'selenium.common.exceptions.TimeoutException']"}], "start": 1624631851094, "stop": 1624631861811, "uuid": "6f0d989c-6ff9-4dd0-87c6-5f75c73d73f0", "historyId": "19633445b0c7f5ef9899164992d20b31", "testCaseId": "352f8543e2d167406e331a06738aacaa", "fullName": "tests.test_wework.TestWework#test_add_member_fail", "labels": [{"name": "story", "value": "添加成员失败"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_wework"}, {"name": "subSuite", "value": "TestWework"}, {"name": "host", "value": "ccyangdeMacBook-Pro.local"}, {"name": "thread", "value": "68010-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_wework"}]}