{"name": "异常用例: 姓名-姓名, 账号-账号, 手机号-1111, 邮箱-", "status": "passed", "attachments": [{"name": "测试图片", "source": "4ff558b1-6a9c-4a37-b795-749deb64face-attachment.png", "type": "image/png"}], "parameters": [{"name": "get_add_member_fail_datas", "value": "['姓名', '账号', 1111, '', 'selenium.common.exceptions.TimeoutException']"}], "start": 1624631891342, "stop": 1624631901872, "uuid": "a32f07c7-679e-4e4a-8a29-c6268b7ed572", "historyId": "64fa274fa5263b1d29b9a57d7b91953d", "testCaseId": "352f8543e2d167406e331a06738aacaa", "fullName": "tests.test_wework.TestWework#test_add_member_fail", "labels": [{"name": "story", "value": "添加成员失败"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_wework"}, {"name": "subSuite", "value": "TestWework"}, {"name": "host", "value": "ccyangdeMacBook-Pro.local"}, {"name": "thread", "value": "68010-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_wework"}]}