{"name": "异常用例: 姓名-姓名, 账号-账号, 手机号-, 邮箱-", "status": "passed", "attachments": [{"name": "测试图片", "source": "19ee3c10-7262-4c73-8799-1abf073252ed-attachment.png", "type": "image/png"}], "parameters": [{"name": "get_add_member_fail_datas", "value": "['姓名', '账号', '', '', 'selenium.common.exceptions.TimeoutException']"}], "start": 1624631878015, "stop": 1624631888291, "uuid": "bed0225d-baa6-4549-9e6c-de7cda00426a", "historyId": "ac25bcc22933d93a2bf3e0d5ebd42fb5", "testCaseId": "352f8543e2d167406e331a06738aacaa", "fullName": "tests.test_wework.TestWework#test_add_member_fail", "labels": [{"name": "story", "value": "添加成员失败"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_wework"}, {"name": "subSuite", "value": "TestWework"}, {"name": "host", "value": "ccyangdeMacBook-Pro.local"}, {"name": "thread", "value": "68010-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_wework"}]}