{"name": "test_case_exception", "status": "passed", "attachments": [{"name": "log", "source": "0d6abae4-f7f3-458f-9696-eb14e18c25fd-attachment.txt", "type": "text/plain"}], "start": 1627199571341, "stop": 1627199571341, "uuid": "4b3f4ff5-fd0e-4b69-b567-550e43157504", "historyId": "3c1349702b885059cc88fbd1df5be690", "testCaseId": "cff0dafaf7d1c57fe586443c358206a9", "fullName": "test_exception#test_case_exception", "labels": [{"name": "suite", "value": "test_exception"}, {"name": "host", "value": "ccyangdeMacBook-Pro.local"}, {"name": "thread", "value": "58394-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_exception"}]}