{"name": "test_case_exception", "status": "passed", "attachments": [{"name": "log", "source": "4b3e15d8-9852-44fa-bc61-c461f4b53fb2-attachment.txt", "type": "text/plain"}], "start": 1627199391469, "stop": 1627199391469, "uuid": "91ac4042-17e8-408e-b8ec-a493bc6cc3a3", "historyId": "3c1349702b885059cc88fbd1df5be690", "testCaseId": "cff0dafaf7d1c57fe586443c358206a9", "fullName": "test_exception#test_case_exception", "labels": [{"name": "suite", "value": "test_exception"}, {"name": "host", "value": "ccyangdeMacBook-Pro.local"}, {"name": "thread", "value": "58268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_exception"}]}